### ISSUE TITLE
Question: Enhancement

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#25] opened 2023-01-13 20:58 UTC
Right now, Legend, Title and other Chart Items in Designer are Local in designer.vb but for my application I want them Friend With Events is there a way to fix this without editing Designer.vb?

The resource designer has an option to control visibility in designer need something like that for custom controls. or just this one.

**Comment by kirsan31** [comment] 2023-01-13 22:29
@paul1956 I am sorry unfortunately I don't know anything about VB :( I don't even understand what you are asking 🤷‍♂️

**Comment by paul1956** [comment] 2023-01-13 22:53
When you create a chart legend, title, etc are private I need them declared with wider scope.

**Comment by kirsan31** [comment] 2023-01-13 22:56
> When you create a chart legend, title, etc are private I need them declared with wider scope.

Unfortunately it didn't get clearer 🙄

**Comment by paul1956** [comment] 2023-01-14 00:04
This is the Controll and for Chart you can set Modifiers.
![image](https://user-images.githubusercontent.com/12789369/212439377-822c2a00-fb13-4047-9bb7-37104290e189.png)
 I don't see how to do that with the items in Chart like ChartArea, Legend, Series, Titles There are no Design Properties.
![image](https://user-images.githubusercontent.com/12789369/212439284-64cc0ad5-43bf-4a99-bf2b-d1b6eb9dc057.png)

Name for example is in "Data" section not Design Properties.

**Comment by kirsan31** [comment] 2023-01-14 00:06
Yea I got it already - in process of answering...

**Comment by paul1956** [comment] 2023-01-14 02:31
Yes, you now understand, if you look at TabPages which is similar the IDE allows you to declare them with other visibility below is Friend. If there are no events raised I agree it is not a good idea to expose.
```
Me.Users = New System.Windows.Forms.TabPage()
Friend WithEvents Users As TabPage
```
I am guessing this is only really important if the Object raises events.

**Comment by kirsan31** [comment] 2023-01-14 18:27
@paul1956 

`TabPage` is not a good example here, because `TabPage` is a `Control` itself. `DataGridView` with `DataGridViewColumn` is more suitable, but `DataGridViewColumn` is component too (derived from `IComponent`)...

`GenerateMember` and `Modifiers` are not real properties. They are automatically added by designer in design time only, when you inherit your class from `IComponent` Interface.
And `TabControl` and `DataGridView` was designed with that `TabPage` and `DataGridViewColumn` are **components** in mind.
But `Chart` control was designed with opposite approach. 

I did a quick test to demonstrate the problems.

The main problem is after we generate member, we will be able to select it and edit properties **directly** - ignoring all Chart collection editors logic. For example, we will loose all elements dependences by names - editing controls directly can lead to unpredictable errors :(
Other problems (I think they solvable): Name property conflict and `GenerateMember` must be `false` by default.
![Snipaste_2023-01-14_11-56-21](https://user-images.githubusercontent.com/17767561/212489026-f7c9e73f-f8f1-412f-9b33-fbd69604cf6c.png)

**Comment by paul1956** [comment] 2023-01-14 22:05
As long as the thing does not raise events, the way you are doing it is fine. I just need to access it by name and VB has an easy way to do that similar to C# using. It's where there are events that VB is different then C# and Visual Studio automatically can create the strongly typed handlers.

**Comment by paul1956** [comment] 2023-01-15 03:46
I don't understand why Name is under Misc when for other controls it is under Design except for that since the only thing that raises event as far as I can tell is Chart there is no real issue and this can be closed.

**Comment by kirsan31** [comment] 2023-01-15 06:51
> I don't understand why Name is under Misc when for other controls it is under Design

If you look at the screenshot above, then it is present both there and there.  And I think it's due to that name of the varibale is differ from name property:

![image](https://user-images.githubusercontent.com/17767561/212527083-ce23108c-9489-4ce5-ab52-beee624b0284.png)


> except for that since the only thing that raises event as far as I can tell is Chart there is no real issue and this can be closed.

Closing it then...

**Closed by kirsan31** 2023-01-15 06:51 UTC
Labels: enhancement, question

**Comment by paul1956** [comment] 2023-01-16 00:05
In case you were wondering what I was up to. This is a medical app for people to monitor an insulin pump with analyze of its data on other tabs. Thanks for making it possible.
![image](https://user-images.githubusercontent.com/12789369/212574737-3ce2314e-d920-494a-97fa-b2e051b42dce.png)

**Comment by kirsan31** [comment] 2023-01-16 07:18
Glad to hear that someone needs it, especially for such a useful cause!
